# Generated by Django 5.1.1 on 2024-12-05 18:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarketDrinkInstance',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Active', models.BooleanField()),
                ('Start', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('End', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('Data', models.JSONField(default=dict)),
            ],
        ),
    ]
