# Generated by Django 5.1.1 on 2024-12-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmarketdrinkinstance',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='stockmarketdrinkinstance',
            name='Data',
        ),
        migrations.RemoveField(
            model_name='stockmarketdrinkinstance',
            name='End',
        ),
        migrations.RemoveField(
            model_name='stockmarketdrinkinstance',
            name='Start',
        ),
        migrations.AddField(
            model_name='stockmarketdrinkinstance',
            name='BeursCrash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockmarketdrinkinstance',
            name='Bier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmarketdrinkinstance',
            name='Fris',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmarketdrinkinstance',
            name='Jenever',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmarketdrinkinstance',
            name='RocketShot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmarketdrinkinstance',
            name='Rode Wijn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmarketdrinkinstance',
            name='Salmari',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmarketdrinkinstance',
            name='Witte Wijn',
            field=models.IntegerField(default=0),
        ),
    ]
