# Generated by Django 5.1.1 on 2024-12-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0002_remove_stockmarketdrinkinstance_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmarketdrinkinstance',
            name='Data',
            field=models.JSONField(default=dict),
        ),
    ]
