# Generated by Django 5.1.1 on 2024-12-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0004_alter_stockmarketdrinkinstance_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarketdrinkinstance',
            name='Data',
            field=models.JSONField(default=dict),
        ),
    ]
